(source gnu)
(source melpa)
(source marmalade)

(depends-on "pallet")
(depends-on "init-loader")

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

(depends-on "elscreen")
(depends-on "color-moccur")
;;(depends-on "moccur-edit")
;;(depends-on "grep-edit")
(depends-on "ag")
(depends-on "gist")
(depends-on "shell-pop")
(depends-on "gtags" :git "https://github.com/voins/gtags.git")

(depends-on "atom-dark-theme")
(depends-on "neotree")
(depends-on "company")

;; helm
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "helm-gtags")
(depends-on "helm-descbinds")
(depends-on "helm-ag")
(depends-on "helm-pydoc")
(depends-on "helm-perldoc")
(depends-on "helm-open-github")

;; Ruby
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-compilation")
(depends-on "ruby-end")
(depends-on "ruby-interpolation")
(depends-on "ruby-test-mode")
(depends-on "ruby-tools")
(depends-on "inf-ruby")
(depends-on "ruby-electric")

;; haml
(depends-on "haml-mode")

;; slim
(depends-on "slim-mode")

;; JavaScript
(depends-on "js2-mode")
(depends-on "ac-js2")
(depends-on "json-mode")

;; CoffeeScript
(depends-on "coffee-mode")
(depends-on "sourcemap")

;; jsx-mode
(depends-on "jsx-mode")

;; Python
(depends-on "jedi")
;;(depends-on "pymacs")

;; Perl
(depends-on "cperl-mode")
(depends-on "xs-mode" :git "https://github.com/emacsmirror/xs-mode.git")

;; Scala
(depends-on "scala-mode2")
(depends-on "ensime")

;; Go
(depends-on "go-mode")
(depends-on "go-autocomplete")

;; groovy
(depends-on "groovy-mode")

;; Erlang
;;(depends-on "erlang-mode")

;; elixir
(depends-on "elixir-mode")
(depends-on "alchemist")
(depends-on "ac-alchemist" :git "https://github.com/syohex/emacs-ac-alchemist")

;; Haskell
(depends-on "haskell-mode")

;; Emacs Lisp
(depends-on "elisp-slime-nav")
(depends-on "paredit")
(depends-on "lispxmp")

;; Common Lisp
(depends-on "slime")
;;(depends-on "scheme-complete")

;; php
(depends-on "php-mode")
(depends-on "php-completion")


;; Validation
(depends-on "flycheck")

;; Shell
(depends-on "quickrun")

;; Markup language
(depends-on "web-mode")
(depends-on "emmet-mode")
(depends-on "yaml-mode")

;; less
(depends-on "less-css-mode")

;; scss
(depends-on "scss-mode")

;; markdown
(depends-on "markdown-mode")
(depends-on "markdown-mode+")

;; terraform
(depends-on "terraform-mode")

;;(depends-on "ipa")
;;(depends-on "multiverse")
(depends-on "popwin")
(depends-on "color-theme")
(depends-on "migemo")
(depends-on "drill-instructor" :git "https://github.com/k1LoW/emacs-drill-instructor.git")
(depends-on "auto-complete")
(depends-on "direx")

(depends-on "ddskk")
(depends-on "w3m")