(require 'anything-config)
(require 'anything)

;(add-to-list 'anything-sources 'anything-c-source-emacs-commands)

(defun my-anything ()
  "Anything command for you.

It is automatically generated by `anything-migrate-sources'."
  (interactive)
  (anything-other-buffer
    '(anything-c-source-emacs-commands anything-c-source-buffers-list anything-c-source-recentf anything-c-source-files-in-current-dir+)
    "*my-anything*"))

(define-key global-map (kbd "C-;") 'my-anything)

